on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: R-CMD-check

jobs:
  R-CMD-check_noLD:
    runs-on: ubuntu-20.04
    container: ghcr.io/r-hub/containers/nold:latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - run: echo "/opt/R-devel/bin" >> $GITHUB_PATH

      - uses: r-lib/actions/setup-r@v2
        with:
          install-r: false
          use-public-rspm: true

      - uses: r-lib/actions/setup-pandoc@v2

      # It looks like pak doesn't support automatic install of sysdeps on Debian
      # at the moment:
      # https://github.com/r-lib/pak/blob/5d826700dba8146c639d41e406ae287d0f06dd3c/R/system-requirements.R#L159
      - name: Install system dependencies
        run: |
          apt-get update
          apt-get install -y libcurl4-openssl-dev libssl-dev imagemagick libmagick++-dev gsfonts libxml2-dev

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages:
            rcmdcheck
            photobiologyInOut=?ignore-before-r=3.6.0

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
